### ISSUE TITLE
Add convenience extent calculation for bin transform?

### ISSUE THREAD

**Issue by jheer** [vega/vega-dataflow#13]
The `bin` transform requires the extent (min/max) values to be provided/calculated externally, a change from Vega 2. Should convenience extent calculation be added back?

**Comment by domoritz** [comment]
Explicit extents have the advantage that a reader immediately knows when the extent changes. 

For instance, if we use a filter before binning, does changing the filter predicate change the extents? If the extent is manually set, no. If it is driven by the data, yes. If it is driven by a signal, the extent changes when the signal changes. 

I suppose that a data driven extent by default makes sense but I think the advantage of explicitly knowing where the extent comes from is larger than the benefit of not having to add an extent transform.

**Comment by kanitw** [comment]
If I have to type Vega spec by hand, I probably would appreciate this.  However, from programming generation perspective (e.g., VL), extent + bin seems fine.

**Comment by kanitw** [comment]
- [x] ~~Note that I still see `"field"` in the bin transform's JSON schema.  If we decide not to include this, we should remove it from the schema~~

**Comment by jheer** [comment]
The `field` parameter is used to specify which tuple values to bin. So we most certainly should NOT remove it!

**Comment by jheer** [comment]
OK, closing this issue for now as it sounds like an explicit extent transform works. Others should feel free to respond / re-open with an argument for including a convenience "auto-extent" functionality.
