### ISSUE TITLE
Documentation of Library for Standalone Usage

### ISSUE THREAD

**Issue by rufuspollock** [vega/vega-dataflow#17]
We're interested in reusing the dataflow component on its own (outside of vega). To do that we'd like to understand more about the design and structure of dataflow.

How would I use it from own code? What is its conceptual model (e.g. how are operations defined, what is the structure of input data etc)?

The current README is a little sparse in this regard.

Our own [analysis so far can be found in this hackmd][hackmd].

[hackmd]: https://hackmd.io/JwEwjGDMCGBMsFoBsAWAHJBLhmggRgAzCbDDRkgCsAZgKaw35A==?both#vega-transforms

Much appreciate any guidance you can provide 😄

**Comment by jheer** [comment]
Yes, there is much documentation missing for stand-alone use. Apologies for that! I hope to get to it later, but it may be a while before I can make a dedicated effort. Documentation and support for the higher-level Vega JSON syntax has taken precedence.

In the meantime, you may find the stand-alone examples in this repo useful: https://github.com/vega/vega-dataflow-examples

**Comment by ericsoco** [comment]
We're interested in doing the same, to be able to process data serverside before passing to the client for rendering. Would love more docs here as you're able!

**Comment by jheer** [comment]
I recommend taking a look at the new [dataflow-api](https://github.com/vega/dataflow-api), which provides a (documented!) standalone JavaScript API over Vega's dataflow system. Feedback welcome!

**Comment by ericsoco** [comment]
Wow, this looks incredible. Did you somehow know we were looking for this, before we did? 😉 
We won't be ready to implement for a bit still but will definitely provide feedback, thank you! Feels like enough to close this issue, but will let @rufuspollock decide.
