### ISSUE TITLE
PreFacet transform doesn't handle MOD correctly 

### ISSUE THREAD

**Issue by boxfish** [vega/vega-dataflow#21]
### Problem
Assume a data item first sent to the PreFacet is 
`[{"_id": 1, "children": [{"name": "child 1"}, {"name": "child 2"}]}],`
where `children` is the field used for accessing the local partition. The marks mapping to the two children are shown properly.

Later a signal change triggers modification to the same data item by filtering the children to empty array: `[{"_id": 1, "children": []}]`,
The expected behavior is that the marks corresponding to the two children should now be removed, but the current behavior is that they are still present.

### Investigation
After the data item is modified, it is processed in PreFacet.js [L33](https://github.com/vega/vega-dataflow/blob/master/src/transforms/PreFacet.js#L33), however since the children is empty, it will basically do nothing, and the two children are still displayed. 
The handling of REM in this case should not just be a REM iteration over the new children, rather it should also handle the ADD/REM elements of the children. 

### Possible Solution
A possible solution may be to remove all existing children and add all new children, but I couldn't find a clean way to get the existing children. the following workaround works in my case, but I doubt whether it is a clean solution yet:

```
  pulse.visit(pulse.MOD, function(t) {
    //field ? field(t).forEach(function(_) { sf.mod(_); }) : sf.mod(t);
    var sf = self.subflow(t._id, flow, pulse, t);
    if (field) {
      // get existing value from targets and remove them
      sf.targets().forEach(function(ta) {
        ta.value.forEach(function(v) {
          sf.rem(v)
        })
      })
      // add new items
      field(t).forEach(function(_) { sf.add(ingest(_)); })
    }
    else {
      sf.mod(t)
    }
  });
```

**Comment by jheer** [comment]
Thanks for the issue! The pre-facet transform is not intended to support modification of the pre-faceted partition field. Your issue made me realize we have a bug in our error condition check.

This check in line 25:
`if (_.modified('field')) {`

should be extended to
`if (_.modified('field') || field && pulse.modified(accessorFields(field))) {`

I have made the above change and re-published vega-dataflow. Extending the transform to support modification of child tuples can be a longer term goal to support. In your example, you look ahead in the dataflow by accessing the `targets` of the subflow. In this case, I believe you happen to be accessing a single `Collect` instance that stores all the previously seen tuples. Unfortunately, the general dataflow library does not provide any guarantees that the children tuples have been collected for revisitation: the actual targets may be arbitrary operators, in which case your solution will break.

In the meantime, an alternative solution might be to remove a parent tuple entirely (rem) and replace it with a new parent tuple with the desired children (add).

**Comment by boxfish** [comment]
Thanks for the explanation!
Regarding to the alternative solution, what is the way to force the parent tuple to be removed and added again? I tried to feed in the changing parent tuples into the View via changeset (changeset.remove().insert()), but it seems the system is smart enough to detect it is a MOD rather than REM and ADD.

**Comment by jheer** [comment]
That's odd. Performing REM and ADD on a changeset should never "automagically" lead to MOD. You should be able to use [`view.change`](https://github.com/vega/vega-view#view_change) for this... if not, it is possible there is a bug somewhere.

**Comment by boxfish** [comment]
Thanks! I will do some debug and report back.

**Comment by boxfish** [comment]
It turned out not an issue with the changeset, rather there is an aggregate transform upstream before the parent tuples go to the PreFacet. Since the key is same for the aggregate transform, the _id is reused from _prev and thus lead to MOD.

**Comment by jheer** [comment]
That makes sense as a source of the error. Pre-facet is primarily intended for raw _input_ data that has a nested structure. If the nesting results from a data transform pipeline _in Vega itself_, I think you should be able to refactor it to use a standard facet (not pre-facet) instead. Feel free to share a spec for more feedback.
