### ISSUE TITLE
Density creates too many steps

### ISSUE THREAD

**Issue by domoritz** [vega/vega-dataflow#25]
```
{
          "type": "density",
          "extent": [0, 10],
          "distribution": {
            "function": "normal",
            "mean": 5,
            "stdev": 2
          },
          "steps": 5
        }
```

creates 6 values, although the documentation states "The number of uniformly spaced samples to draw along the extent domain (default 100)."

**Comment by jheer** [comment]
The documentation is in error. This parameter indicates the number of _steps_ (not _samples_) used between the min and max of the domain. The total number of sampled points is thus _step + 1_. I'll update the documentation.
