### ISSUE TITLE
Run Listener

### ISSUE THREAD

**Issue by jhoffswell** [vega/vega-dataflow#29]
Add a (private) run listener to perform operations after each pulse.

**Comment by jheer** [comment]
Added in 08735a91785b14e96f45c1293cda12760ee5816d, released in vega-dataflow v2.0.6.

Usage example:
```js
view._onrun = function(view, count, error) { console.log('RUN', view.stamp(), count + ' operators'); };
```

The first argument is the dataflow instance. Second argument is the number of operators evaluated during pulse propagation. Third argument is the value of any error thrown in the midst of dataflow execution. Note: Do **not** invoke the `run` method recursively from within `_onrun`!
