### ISSUE TITLE
Repo restructuring caused broken link

### ISSUE THREAD

**Issue by ericsoco** [vega/vega-dataflow#33]
[This commit](https://github.com/vega/vega-dataflow/commit/ef6e3a47e9059d1be5f022ad3ad9f68ca3daaaf7) broke the link to definition object examples on [this doc page](https://vega.github.io/vega/docs/api/extensibility/#register). Not sure yet where the definition objects have moved, still looking...

**Comment by jheer** [comment]
Thanks! I'll update the documentation shortly. The definition objects are now included with the transform implementations directly (i.e., as `transform.Definition`). For example, see the transforms defined in the [vega-transforms repo](https://github.com/vega/vega-transforms/).

**Comment by jheer** [comment]
[Extensibility docs](https://vega.github.io/vega/docs/api/extensibility/#transforms) have now been updated.
