### ISSUE TITLE
Show friendlier error if a signal is undefined. 

### ISSUE THREAD

**Issue by kanitw** [vega/vega-dataflow#6]
If a signal is undefined in [Graph.js line 216](https://github.com/vega/vega-dataflow/blob/master/src/Graph.js#L216), an Uncaught TypeError: Cannot read property 'addListener' of undefined will be thrown.   

We should catch this error and produce a friendlier “Invalid Signal Name” error (or something like this) instead.

**Comment by arvind** [comment]
Good call. Addressed in 181939d.
